[package]
name = "rust"
version = "0.1.0"
authors = ["Michal Michalewski <michal.michalewski@finder.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.12.0"
nipper = "0.1.9"
